### ISSUE TITLE
Why is this not part of the Platform?

### ISSUE THREAD

**Issue by PyvesB** [fipro78/e4-preferences#1]
Hello there,

Simple question: why are preference pages not included as part of the Platform? Seeing some of the discussions on forums, StackOverflow and various blogs, this seems like a pain-point for quite a few developers. In addition, there are different approaches (this one, opcoach/e4Preferences, probably other alternatives), which creates inconsistencies in the way plugins are built. I'm myself not keen on bringing external dependencies and having to write additional boiler plate code considering how straightforward things are with the old `org.eclipse.ui` classes.

Thanks for reading!

Pyves

**Comment by fipro78** [comment]
Hi,

I don't know why there is still no pure E4 preference implementation in the platform. Probably because no-one started to contribute.

The solution of Olivier (opcoach) is an extension point based approach. My solution is an OSGi DS approach as I don't like extensions points nowadays.

And one other thing. I am not sure if you want to blame me for having created this implementation on GitHub or what your intention was to open this GitHub issue. So I don't know what you are expecting from me now.

Greez,
Dirk

**Comment by PyvesB** [comment]
> And one other thing. I am not sure if you want to blame me for having created this implementation on GitHub or what your intention was to open this GitHub issue.

No, there was absolutely no blame intention whatsoever, sorry if the message came across in that way. Even though I've already built a few plugins and have contributed several patches to the IDE and related projects, I'm still having trouble to understand how some of these things tie together. The objective was to start a discussion and clarify things.

> So I don't know what you are expecting from me now.

Well, would there be value in contributing this back to the Platform? Do you know of any bugs related to E4 preference pages (I haven't found any after a quick Bugzilla search)?

**Comment by fipro78** [comment]
> No, there was absolutely no blame intention 

Good to know. :)

> Well, would there be value in contributing this back to the Platform? Do you know of any bugs related to E4 preference pages (I haven't found any after a quick Bugzilla search)?

No I am not aware of any related bug ticket.

**Comment by fipro78** [comment]
If you have plans to bring this to the platform, just let me know and I will try to help. Probably the first step would be to open a ticket in Bugzilla and start a discussion there. Probably a solution that combines the one from opcoach and my approach would be the solution for the platform. We would need to become backwards compatible with my solution, which means, the extension point mechanism and the DS mechanism would need to work together somehow. This is actually missing in my solution as of now.

As you only wanted to start a discussion here, and there was no further comments, I close this issue now.
